# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#markdown: kramdown

#kramdown:
#  input: Kramdown
#  syntax_highlighter: coderay

title: 博客列表
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: just-the-docs # for local development
remote_theme: just-the-docs/just-the-docs # for GitHub deployment

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
search_enabled: true
# For copy button on code
enable_copy_code_button: true
heading_anchors: true
nav_enabled: true
nav_sort: case_sensitive # Capital letters sorted before lowercase
nav_error_report: true # default is false/nil.
liquid:
  error_mode: strict
  strict_filters: true
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
#kramdown:
#  syntax_highlighter_opts
##    block:
##      line_numbers: false
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

aux_links_new_tab: true

aux_links:
  "github source code":
    - "//github.com/Q-Peppa/Q-Peppa.github.io"


enable_color_scheme_toggle: true 