name: Build my App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
    buildWin:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2
        - name: install
          uses: ilammy/msvc-dev-cmd@v1
          with:
            node-version: 16.x
        - run: npm install && npm run build
