# github 自动部署任务, 自动执行 npm install
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build project by q
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
